### ISSUE TITLE
Expected <block end>, but found '<scalar>'

### ISSUE THREAD

**Issue by jorvis** [common-workflow-language/cwl-upgrader#10]
Here is the [CWL in question](https://github.com/jorvis/GALES/blob/ef8b5f870cc5dced5e8179f8a090ae63befb061c/cwl/workflows/prok-annotation-cheetah.cwl).  Then, when I try to convert it I get:

$ cwl-upgrader prok-annotation-cheetah.cwl 
Traceback (most recent call last):
  File "/usr/local/bin/cwl-upgrader", line 11, in <module>
    load_entry_point('cwl-upgrader==0.2.2', 'console_scripts', 'cwl-upgrader')()
  File "/usr/local/lib/python3.5/dist-packages/cwlupgrader/main.py", line 13, in main
    document = ruamel.yaml.round_trip_load(entry)
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/main.py", line 123, in round_trip_load
    return load(stream, RoundTripLoader, version, preserve_quotes=preserve_quotes)
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/main.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/constructor.py", line 55, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/composer.py", line 50, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/composer.py", line 70, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/composer.py", line 105, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/composer.py", line 164, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/composer.py", line 103, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/composer.py", line 134, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/composer.py", line 105, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/composer.py", line 157, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/parser.py", line 116, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.5/dist-packages/ruamel/yaml/parser.py", line 505, in parse_block_mapping_key
    token.start_mark)
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "prok-annotation-cheetah.cwl", line 182, column 5
expected <block end>, but found '<scalar>'
  in "prok-annotation-cheetah.cwl", line 183, column 27

**Comment by jorvis** [comment]
Closing as this was my own issue.  I had variables within the CWL like {{tool_path}} which were replaced in pre-processing.  Removing these temporarily make this work properly.
