### ISSUE TITLE
Imports inside the requirements block cause cwl-upgrader to fail 

### ISSUE THREAD

**Issue by TMiguelT** [common-workflow-language/cwl-upgrader#23]
The `$import` key seems to cause this to fail. For example, here is the minimal CWL that will cause this problem: 
```yaml
cwlVersion: "cwl:draft-3"
class: CommandLineTool
requirements:
- $import: file.yml
```

The error I get is:
```
Traceback (most recent call last):
  File "/usr/local/bin/cwl-upgrader", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/cwlupgrader/main.py", line 24, in main
    document = draft3_to_v1_0(document)
  File "/usr/local/lib/python3.6/dist-packages/cwlupgrader/main.py", line 34, in draft3_to_v1_0
    _draft3_to_v1_0(document)
  File "/usr/local/lib/python3.6/dist-packages/cwlupgrader/main.py", line 57, in _draft3_to_v1_0
    hints_and_requirements_clean(document)
  File "/usr/local/lib/python3.6/dist-packages/cwlupgrader/main.py", line 161, in hints_and_requirements_clean
    if entry["class"] == "CreateFileRequirement":
KeyError: 'class'
```

**Comment by TMiguelT** [comment]
I've looked into fixing this by simply skipping keys without a `class`, but the problem is I'm not sure how to even write out these import statements if we're using the dictionary-style requirements block, which is how cwl-upgrader outputs its CWL.
