### ISSUE TITLE
tests: upgrade all the CWL v1.0 conformance tests and confirm the results

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-upgrader#87]

**Comment by mr-c** [comment]
I did this manually, and with #90 and #88 merged, this works for `v1.0` to `v1.1`

**Comment by jdidion** [comment]
Please also test on mixed-versions tests, e.g. https://github.com/common-workflow-language/cwl-v1.2/blob/1.2.1_proposed/tests/mixed-versions/wf-v12.cwl

I get the following error when trying with the current release version:

```
Processing wf-v12.cwl
Unsupported cwlVersion: v1.2
Traceback (most recent call last):
  File "/Users/jdidion/.pyenv/versions/cwltool/bin/cwl-upgrader", line 11, in <module>
    sys.exit(main())
  File "/Users/jdidion/.pyenv/versions/3.6.14/envs/cwltool/lib/python3.6/site-packages/cwlupgrader/main.py", line 59, in main
    return run(parse_args(args))
  File "/Users/jdidion/.pyenv/versions/3.6.14/envs/cwltool/lib/python3.6/site-packages/cwlupgrader/main.py", line 80, in run
    document, args.v1_only, args.v1_1_only, args.dir, imports
  File "/Users/jdidion/.pyenv/versions/3.6.14/envs/cwltool/lib/python3.6/site-packages/cwlupgrader/main.py", line 118, in upgrade_document
    process_imports(document, imports, inner_updater, output_dir)
UnboundLocalError: local variable 'inner_updater' referenced before assignment
```

**Comment by tetron** [comment]
This should be fixed in main, need to make a new release.

**Comment by mr-c** [comment]
fixed in https://github.com/common-workflow-language/cwl-upgrader/pull/139
