### ISSUE TITLE
unicode failure on Python 3.5

### ISSUE THREAD

**Issue by jorvis** [common-workflow-language/cwl-upgrader#9]
Some tools I converted worked fine on my machine that uses Python 3.4, but on another the same files failed with Python 3.5 with this message:

```
$ cwl-upgrader prodigal.cwl > prodigal.cwl.1
Traceback (most recent call last):
  File "/usr/local/bin/cwl-upgrader", line 9, in <module>
    load_entry_point('cwl-upgrader==0.2', 'console_scripts', 'cwl-upgrader')()
  File "/usr/local/lib/python3.5/dist-packages/cwlupgrader/main.py", line 12, in main
    draft3_to_v1_0(document)
  File "/usr/local/lib/python3.5/dist-packages/cwlupgrader/main.py", line 17, in draft3_to_v1_0
    _draft3_to_v1_0(document)
  File "/usr/local/lib/python3.5/dist-packages/cwlupgrader/main.py", line 40, in _draft3_to_v1_0
    setupCLTMappings(document)
  File "/usr/local/lib/python3.5/dist-packages/cwlupgrader/main.py", line 63, in setupCLTMappings
    param['type'] = shortenType(param['type'])
  File "/usr/local/lib/python3.5/dist-packages/cwlupgrader/main.py", line 73, in shortenType
    if isinstance(typeObj, (str, unicode)) or not isinstance(typeObj, Sequence):
NameError: name 'unicode' is not defined
```
This is one of the example files: [prodigal.cwl](https://github.com/jorvis/GALES/blob/a654be33e7ecd90124e61aff245b3385573d60c6/cwl/tools/prodigal.cwl)

**Comment by mr-c** [comment]
Seems to be fixed now, via local testing
