### ISSUE TITLE
Upgrade a cwl 1.2 workflow fails

### ISSUE THREAD

**Issue by golharam** [common-workflow-language/cwl-upgrader#93]
Using cwl-upgrader-1.2.2

$ cwl-upgrader rsem-merge.cwl 
Processing rsem-merge.cwl
Unsupported cwlVersion: v1.2
Traceback (most recent call last):
  File "/Users/golharr/workspace/NGS/RNASeq/env/bin/cwl-upgrader", line 8, in <module>
    sys.exit(main())
  File "/Users/golharr/workspace/NGS/RNASeq/env/lib/python3.6/site-packages/cwlupgrader/main.py", line 59, in main
    return run(parse_args(args))
  File "/Users/golharr/workspace/NGS/RNASeq/env/lib/python3.6/site-packages/cwlupgrader/main.py", line 80, in run
    document, args.v1_only, args.v1_1_only, args.dir, imports
  File "/Users/golharr/workspace/NGS/RNASeq/env/lib/python3.6/site-packages/cwlupgrader/main.py", line 118, in upgrade_document
    process_imports(document, imports, inner_updater, output_dir)
UnboundLocalError: local variable 'inner_updater' referenced before assignment

I would expect this to validate the cwl 1.2 workflow and ensure nothing is wrong, since there isn't an upgrade needed.

**Comment by tetron** [comment]
Hi @golharam 

Yes that's an unfortunate oversight, running the upgrader on a v1.2 document should be a no-op but instead it fails because it didn't choose an updater (because there's nothing to update).  I'll see about whipping up a quick fix.

**Comment by mr-c** [comment]
Fixed in #94
